#!/bin/sh

if [ -f /overlay/wifi.json ]; then
    ssid=$(jq -r '.ssid' /overlay/wifi.json)
    password=$(jq -r '.password' /overlay/wifi.json)
    if [ -n "$ssid" ] && [ -n "$password" ]; then
        current_ssid=$(nmcli -t -f active,ssid dev wifi | grep '^yes:' | cut -d: -f2)
        if [ -n "$current_ssid" ]; then
            echo "current connected wifi: $current_ssid, disconnect it"
            nmcli con down id "$current_ssid"
            nmcli con delete "$current_ssid"
        fi
        if ! nmcli dev wifi connect "$ssid" password "$password"; then
            echo "can't connect to wifi, please check ssid and password"
            exit 1
        fi
        mkdir -p /emmc/oem/cfg
        if [ -f /emmc/oem/cfg/wpa_supplicant.conf ]; then
            echo "wpa_supplicant.conf already exists, update it"
            sed -i "s/ssid=.*/ssid=\"$ssid\"/g" /emmc/oem/cfg/wpa_supplicant.conf
            sed -i "s/psk=.*/psk=\"$password\"/g" /emmc/oem/cfg/wpa_supplicant.conf
            exit 0
        else
            echo "ctrl_interface=/var/run/wpa_supplicant" >> /emmc/oem/cfg/wpa_supplicant.conf
            echo "ap_scan=1" >> /emmc/oem/cfg/wpa_supplicant.conf
            echo "update_config=1" >> /emmc/oem/cfg/wpa_supplicant.conf
            echo "network={" >> /emmc/oem/cfg/wpa_supplicant.conf
            echo "    ssid=\"$ssid\"" >> /emmc/oem/cfg/wpa_supplicant.conf
            echo "    psk=\"$password\"" >> /emmc/oem/cfg/wpa_supplicant.conf
            echo "    key_mgmt=WPA-PSK" >> /emmc/oem/cfg/wpa_supplicant.conf
            echo "}" >> /emmc/oem/cfg/wpa_supplicant.conf
            echo "set /emmc/oem/cfg/wpa_supplicant.conf according to wifi.json. The content is:"
            cat /emmc/oem/cfg/wpa_supplicant.conf
            exit 0
        fi
    else
        echo "No ssid or password found, skip setting"
        exit 1
    fi
else 
    echo "No wifi.json found, skip setting"
    exit 1
fi